# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dc34042ad08d2373d9e1454dd47e050732de0330bcc6348fc2ddb82dd15d57b6cebae225cd2eff3b507882efd0e5e8fdeda931cba3b8122ecc7d2190b6b76a2a

test:
  secret_key_base: 788098d2acc109df09db8cc634d86d07e110f013c0bb1cd2dc7c6e4399b65252928aac787f70ef4f9176c4a110495d9645b29f7f60232c90b002c722876a545a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
